USE prepargne;

-- Nukes if messed up foreign key constraint stuff
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS tokenizeds;
DROP TABLE IF EXISTS spendings;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO tokenizeds VALUES (0, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJDYWRlbmNlIiwiaWF0IjoxNzc1OTIyMjg0LCJleHAiOjE3NzYwMDg2ODR9.AVwquLNcv_9ROs62TeE-B8b1731wOr23mGhS3Ov9UMY', 90000, 100, LOCALTIME(), LOCALTIME());
INSERT INTO spendings VALUES (0, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJDYWRlbmNlIiwiaWF0IjoxNzc1OTIyMjg0LCJleHAiOjE3NzYwMDg2ODR9.AVwquLNcv_9ROs62TeE-B8b1731wOr23mGhS3Ov9UMY', '1000', 'tozeur', LOCALTIME(), LOCALTIME());
INSERT INTO spendings VALUES (10, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJDYWRlbmNlIiwiaWF0IjoxNzc1OTIyMjg0LCJleHAiOjE3NzYwMDg2ODR9.AVwquLNcv_9ROs62TeE-B8b1731wOr23mGhS3Ov9UMY', '100', 'zaizaizaizai', LOCALTIME(), LOCALTIME());

-- TRIGGER to delete 0 amount spending rows ?

SELECT * FROM spendings;
SELECT * FROM tokenizeds;
SELECT * FROM users;
